version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    env_file: .env
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
    environment:
      - REACT_APP_API_URL=http://localhost:${PORT_BACKEND}
    env_file: .env
    depends_on:
      - backend
    restart: always
